version: '3'

services:

  mongo:
    image: mongo
    container_name: 'falcon-mongo'
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: 'falcon-mongo-express'
    links:
      - mongo
    ports:
      - "8081:8081"
